
if hash docker-machine 2>/dev/null; then
    # Configure shell for docker
    eval "$(docker-machine env default </dev/null)"

    drmall ()
    {
        docker rm -f $(docker ps -a -q)
    }

    drminone ()
    {
        docker rmi $(docker images | grep "^<none>" | awk "{print $3}")
    }
fi
