
if hash docker-machine 2>/dev/null; then

    drmall ()
    {
        docker rm -f $(docker ps -a -q)
    }

    drminone ()
    {
        docker rmi $(docker images | grep "^<none>" | awk "{print $3}")
    }
fi
