if [ "$(uname)" == "Darwin" ]; then

    # add alias to enable automatic switching to foremost Finder directory
    alias cdf='cd `osascript -e "tell application \"Finder\" to if window 1 exists then if target of window 1 as string is not \":\" then get POSIX path of (target of window 1 as alias)"`'


fi

